<?php

namespace AppBundle\Repository;

/**
 * IndividuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndividuRepository extends \Doctrine\ORM\EntityRepository
{
}
